<?php

namespace Database\Seeders;

use App\Models\familydata;
use Illuminate\Database\Seeder;

class FamilydataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //családi adatok felvitele
        familydata::factory()->create([
            'nev'=> 'Dobszayné Párdányi Klára',
            'mobil_telefonszam'=> '+36705720758',
            'vonalas_telefon'=> '0613150682',
            'cim'=> '1024 Budapest, Keleti K. u. 11/a',
            'szuletesi_ev'=> 1934,
            'szulinap'=> '12.31',
            'nevnap'=> '08.11.',
            'email'=> 'dobszaylaszlone@gmail.com',
            'skype'=> null,
            'csaladsorszam'=> 0,
            'matebazsi_kod'=> 0,
            'sor_szamlalo'=> 0,
            'becenev_sor'=> '',
            'bankszamla'=> '',
            'revolut_id'=> '',
            'ki_ki'=> '',
            'naptar'=> 1,
            'elso_generacio'=> null,
            'unoka_generacio'=> null,
            'dedunoka_generacio'=> null,
        ]);
        familydata::factory()->create([
            'nev'=>  'Dobszay Ágnes',
            'mobil_telefonszam'=>  '06305776005',
            'vonalas_telefon'=>  '',
            'cim'=>  '1039 Bp. Zsirai Miklós u. 15. 8/24',
            'szuletesi_ev'=> 1961,
            'szulinap'=>  '04.27.',
            'nevnap'=>  '01.21.',
            'email'=>  'dobszagi@gmail.com',
            'skype'=>  null,
            'csaladsorszam'=> 1,
            'matebazsi_kod'=> 1,
            'sor_szamlalo'=>  null,
            'becenev_sor'=>  '',
            'bankszamla'=>  '',
            'revolut_id'=>  '',
            'ki_ki'=>  '',
            'naptar'=> 1,
            'elso_generacio'=> 1,
            'unoka_generacio'=>  null,
            'dedunoka_generacio'=>  null,
       ]);

       familydata::factory()->create([
        'nev'=> 'Farkas Zoltán',
        'mobil_telefonszam'=> '+36302683000',
        'vonalas_telefon'=> '',
        'cim'=> null,
        'szuletesi_ev'=> 1964,
        'szulinap'=> '05.07',
        'nevnap'=> '03.08.',
        'email'=> 'mintordas@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 1,
        'matebazsi_kod'=> 10,
        'sor_szamlalo'=> 0,
        'becenev_sor'=> '',
        'bankszamla'=> '',
        'revolut_id'=> '',
        'ki_ki'=> '',
        'naptar'=> null,
        'elso_generacio'=> 1,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> null,
       ]);

       familydata::factory()->create([
        'nev'=> 'Farkas Máté',
        'mobil_telefonszam'=> '+36306776271',
        'vonalas_telefon'=> 3612472816,
        'cim'=> '1032 Budapest, Bécsi út 171. III./5a.',
        'szuletesi_ev'=> 1988,
        'szulinap'=> '06.24',
        'nevnap'=> '09.21',
        'email'=> 'reklamnelkul@gmail.com',
        'skype'=> 'fola8888',
        'csaladsorszam'=> 1,
        'matebazsi_kod'=> 11,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=> '11773030-00268817',
        'revolut_id'=> 'revolut.me/mto3pl8',
        'ki_ki'=> 'uno',
        'naptar'=> 1,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
       ]);
       
       familydata::factory()->create([
        'nev'=> 'Czakó-Farkas Luca Orsolya',
        'mobil_telefonszam'=> 636308832903,
        'vonalas_telefon'=> '',
        'cim'=> '2011 Budakalász Munkácsy Mihály utca 21',
        'szuletesi_ev'=> 1991,
        'szulinap'=> '11.08.',
        'nevnap'=> '12.13.',
        'email'=> 'farkaslucao@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 1,
        'matebazsi_kod'=> 12,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> 1,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Czakó Adorján',
        'mobil_telefonszam'=> '06305831238',
        'vonalas_telefon'=> '',
        'cim'=> '2011 Budakalász Munkácsy Mihály utca 21',
        'szuletesi_ev'=> 1988,
        'szulinap'=> '01.08.',
        'nevnap'=> '03.05.',
        'email'=> 'czako.adorjan@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 1,
        'matebazsi_kod'=> 120,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno-vej',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Czakó Veronika Ágnes',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '2011 Budakalász Munkácsy Mihály utca 21',
        'szuletesi_ev'=> 2016,
        'szulinap'=> '08.30.',
        'nevnap'=> '01.13',
        'email'=> 'verusamanus@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 1,
        'matebazsi_kod'=> 121,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1

      ]);

       familydata::factory()->create([
        'nev'=> 'Czakó Rozália Éva',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '2011 Budakalász Munkácsy Mihály utca 21',
        'szuletesi_ev'=> 2018,
        'szulinap'=> '08.29.',
        'nevnap'=> '03.13.',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 1,
        'matebazsi_kod'=> 122,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1

      ]);
       familydata::factory()->create([
        'nev'=> 'Czakó Adél Luca',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '2011 Budakalász Munkácsy Mihály utca 21',
        'szuletesi_ev'=> 2020,
        'szulinap'=> '12.21.',
        'nevnap'=> '01.29',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 1,
        'matebazsi_kod'=> 123,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Tamás',
        'mobil_telefonszam'=> '06303930685',
        'vonalas_telefon'=> 2571931,
        'cim'=> '1145 Bp. Törökőr u. 66.',
        'szuletesi_ev'=> 1962,
        'szulinap'=> '06.18.',
        'nevnap'=> '03.07',
        'email'=> 'dobtam@freemail.hu',
        'skype'=> null,
        'csaladsorszam'=> 2,
        'matebazsi_kod'=> 2,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 1,
        'naptar'=> 1,
        'elso_generacio'=> 1,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> null,
        'szulo_id' =>  1
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszayné Hennel Judit',
        'mobil_telefonszam'=> '06307801321',
        'vonalas_telefon'=> 2571931,
        'cim'=> '1145 Bp. Törökőr u. 66.',
        'szuletesi_ev'=> null,
        'szulinap'=> '05.13.',
        'nevnap'=> '12.10.',
        'email'=> 'dobszay.judit@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 2,
        'matebazsi_kod'=> 20,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> null,
        'naptar'=> null,
        'elso_generacio'=> 1,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Zsófia',
        'mobil_telefonszam'=> '06203204756',
        'vonalas_telefon'=> '',
        'cim'=> '1118 Bp. Somlói út 5/B.',
        'szuletesi_ev'=> 1989,
        'szulinap'=> '02.05.',
        'nevnap'=> '05.15.',
        'email'=> 'dobszayzsofi@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 2,
        'matebazsi_kod'=> 21,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> 1,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Bognár András Bálint',
        'mobil_telefonszam'=> '06205989876',
        'vonalas_telefon'=> '',
        'cim'=> '1118 Bp. Somlói út 5/B.',
        'szuletesi_ev'=> 1987,
        'szulinap'=> '12.23.',
        'nevnap'=> '11.30.',
        'email'=> 'buundy@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 2,
        'matebazsi_kod'=> 210,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno-vej',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Bognár Márton Bálint',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '1118 Bp. Somlói út 5/B.',
        'szuletesi_ev'=> 2018,
        'szulinap'=> '10.11.',
        'nevnap'=> '11.11.',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 2,
        'matebazsi_kod'=> 211,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Bognár Mihály András',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '1118 Bp. Somlói út 5/B.',
        'szuletesi_ev'=> 2020,
        'szulinap'=> '04.15.',
        'nevnap'=> '09.29.',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 2,
        'matebazsi_kod'=> 212,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Bognár Júlia Rita',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '1118 Bp. Somlói út 5/B.',
        'szuletesi_ev'=> 2022,
        'szulinap'=> '10.26.',
        'nevnap'=> '05.22.',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 2,
        'matebazsi_kod'=> 213,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Péter',
        'mobil_telefonszam'=> '0670 6350052',
        'vonalas_telefon'=> '',
        'cim'=> '1158 Bp. Ady Endre utca 49./A',
        'szuletesi_ev'=> 1990,
        'szulinap'=> '11.13.',
        'nevnap'=> '06.29.',
        'email'=> 'dobszay.peter@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 2,
        'matebazsi_kod'=> 22,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> 1,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay-Meskó Ilona',
        'mobil_telefonszam'=> '0670 9421656',
        'vonalas_telefon'=> '',
        'cim'=> '1158 Bp. Ady Endre utca 49./A',
        'szuletesi_ev'=> 1981,
        'szulinap'=> '06.21.',
        'nevnap'=> '08.18.',
        'email'=> 'meskoilona@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 2,
        'matebazsi_kod'=> 220,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno-meny',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay László',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '1158 Bp. Ady Endre utca 49./A',
        'szuletesi_ev'=> 2015,
        'szulinap'=> '04.27.',
        'nevnap'=> '06.27.',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 2,
        'matebazsi_kod'=> 221,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Anna',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '1158 Bp. Ady Endre utca 49./A',
        'szuletesi_ev'=> 2017,
        'szulinap'=> '12.20.',
        'nevnap'=> '07.26.',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 2,
        'matebazsi_kod'=> 222,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Dávid',
        'mobil_telefonszam'=> '06307561817',
        'vonalas_telefon'=> 2571931,
        'cim'=> '1145 Bp. Törökőr u. 66.',
        'szuletesi_ev'=> 1993,
        'szulinap'=> '12.20.',
        'nevnap'=> '05.29.',
        'email'=> 'david.dobszay@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 2,
        'matebazsi_kod'=> 23,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay János',
        'mobil_telefonszam'=> '+36309506932',
        'vonalas_telefon'=> 3875535,
        'cim'=> '1037 Budapest, Tarhos utca 48.',
        'szuletesi_ev'=> 1963,
        'szulinap'=> '12.05.',
        'nevnap'=> '06.24.',
        'email'=> 'j.dobszay@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 3,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 1,
        'naptar'=> 1,
        'elso_generacio'=> 1,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Jánosné (Titi)',
        'mobil_telefonszam'=> '+36302146103',
        'vonalas_telefon'=> 3875535,
        'cim'=> '1037 Budapest, Tarhos utca 48.',
        'szuletesi_ev'=> 1963,
        'szulinap'=> '12.20.',
        'nevnap'=> '08.05.',
        'email'=> 'dy.krisztina@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 30,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> null,
        'naptar'=> null,
        'elso_generacio'=> 1,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Huszka-Dobszay Klára',
        'mobil_telefonszam'=> '+36204195036',
        'vonalas_telefon'=> '',
        'cim'=> '1037 Budapest, Pirkadat u. 27B',
        'szuletesi_ev'=> 1986,
        'szulinap'=> '04.11',
        'nevnap'=> '08.11',
        'email'=> 'klara.huszka.dobszay@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 31,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> 1,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Huszka Ágoston',
        'mobil_telefonszam'=> '+36303483380',
        'vonalas_telefon'=> '',
        'cim'=> '1037 Budapest, Pirkadat u. 27B',
        'szuletesi_ev'=> 1985,
        'szulinap'=> '09.11',
        'nevnap'=> '08.28',
        'email'=> 'agoston.huszka@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 310,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno-vej',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Huszka Botond',
        'mobil_telefonszam'=> 36203308042,
        'vonalas_telefon'=> '',
        'cim'=> '1037 Budapest, Pirkadat u. 27B',
        'szuletesi_ev'=> 2011,
        'szulinap'=> '09.29.',
        'nevnap'=> '05. 16.',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 311,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Huszka Csongor',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '1037 Budapest, Pirkadat u. 27B',
        'szuletesi_ev'=> 2015,
        'szulinap'=> '12. 14.',
        'nevnap'=> '04.16.',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 312,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Huszka Zsombor',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '1037 Budapest, Pirkadat u. 27B',
        'szuletesi_ev'=> 2019,
        'szulinap'=> '04.26.',
        'nevnap'=> '11.08.',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 313,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Miklós',
        'mobil_telefonszam'=> '0670 6719584',
        'vonalas_telefon'=> '',
        'cim'=> 'Pomáz Béke utca 11/N',
        'szuletesi_ev'=> 1987,
        'szulinap'=> '06.11.',
        'nevnap'=> '12.06.',
        'email'=> 'dobszaymiklos@gmail.com',
        'skype'=> 'dobszaymiklos',
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 32,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> 1,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszayné Janto Timea',
        'mobil_telefonszam'=> '0630 8307185',
        'vonalas_telefon'=> '',
        'cim'=> 'Pomáz Béke utca 11/N',
        'szuletesi_ev'=> 1989,
        'szulinap'=> '10.03.',
        'nevnap'=> '05.03',
        'email'=> 'timcsussz@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 320,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno-meny',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Lívia',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> 'Pomáz Béke utca 11/N',
        'szuletesi_ev'=> 2015,
        'szulinap'=> '03.17',
        'nevnap'=> '02.12',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 321,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Vilmos',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> 'Pomáz Béke utca 11/N',
        'szuletesi_ev'=> 2017,
        'szulinap'=> '01.08',
        'nevnap'=> '05.23',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 322,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Benjámin',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> 'Pomáz Béke utca 11/N',
        'szuletesi_ev'=> 2020,
        'szulinap'=> 12.27,
        'nevnap'=> '03.31.',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 323,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Steinbach-Dobszay Eszter',
        'mobil_telefonszam'=> '+36209159234',
        'vonalas_telefon'=> '',
        'cim'=> '1038 Bp. Honvéd utca 18. Fsz. 2',
        'szuletesi_ev'=> 1990,
        'szulinap'=> '01.18',
        'nevnap'=> '05.24',
        'email'=> 'dobszayeszter@gmail.com',
        'skype'=> 'dobszay_eszter',
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 33,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> 1,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Steinbach Ágoston',
        'mobil_telefonszam'=> '+36209159350\n +4915234709051',
        'vonalas_telefon'=> '',
        'cim'=> '1038 Bp. Honvéd utca 18. Fsz. 2',
        'szuletesi_ev'=> 1990,
        'szulinap'=> '03.13',
        'nevnap'=> '08.28',
        'email'=> 'agoston.steinbach@gmail.com',
        'skype'=> 'steinbach.agoston',
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 330,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno-vej',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Steinbach Borbála',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '1038 Bp. Honvéd utca 18. Fsz. 2',
        'szuletesi_ev'=> 2017,
        'szulinap'=> '03.09',
        'nevnap'=> 12.04,
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 331,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Steinbach Balázs',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '1038 Bp. Honvéd utca 18. Fsz. 2',
        'szuletesi_ev'=> 2018,
        'szulinap'=> '04.03',
        'nevnap'=> '02.03.',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 332,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Steinbach Dávid',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '1038 Bp. Honvéd utca 18. Fsz. 2',
        'szuletesi_ev'=> 2022,
        'szulinap'=> '04.06.',
        'nevnap'=> '12.30.',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 333,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'D. Szűcs-Dobszay Katalin',
        'mobil_telefonszam'=> '+36202446739',
        'vonalas_telefon'=> '',
        'cim'=> '1117 Bp Alíz utca 6/b F épület 2/8',
        'szuletesi_ev'=> 1992,
        'szulinap'=> '09.18',
        'nevnap'=> '04.30',
        'email'=> 'dobszykat@gmail.com',
        'skype'=> 'dobszykat',
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 34,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> 1,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'D. Szűcs Gergely',
        'mobil_telefonszam'=> '+36304677615',
        'vonalas_telefon'=> '',
        'cim'=> '1117 Bp Alíz utca 6/b F épület 2/8',
        'szuletesi_ev'=> 1990,
        'szulinap'=> '02.08',
        'nevnap'=> '05.09',
        'email'=> 'gergely.dszucs@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 340,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno-vej',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'D. Szűcs Ábel',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> 'Mennyország <3',
        'szuletesi_ev'=> 2018,
        'szulinap'=> 10.28,
        'nevnap'=> '',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 341,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'D. Szűcs Boglárka',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '1117 Bp Alíz utca 6/b F épület 2/8',
        'szuletesi_ev'=> 2020,
        'szulinap'=> '03.19',
        'nevnap'=> '08.01',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 342,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'D. Szűcs Janka',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '1117 Bp Alíz utca 6/b F épület 2/8',
        'szuletesi_ev'=> 2021,
        'szulinap'=> '11.29.',
        'nevnap'=> '05.30.',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 343,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'D. Szűcs Bende',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '1117 Bp Alíz utca 6/b F épület 2/8',
        'szuletesi_ev'=> 2024,
        'szulinap'=> 11.25,
        'nevnap'=> '04.14',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 344,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Dorka',
        'mobil_telefonszam'=> 36203530331,
        'vonalas_telefon'=> 3875535,
        'cim'=> '1037 Budapest, Tarhos 48.',
        'szuletesi_ev'=> 2002,
        'szulinap'=> '10.13.',
        'nevnap'=> '02.06.',
        'email'=> 'dobszaydorka@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 3,
        'matebazsi_kod'=> 35,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Gergely',
        'mobil_telefonszam'=> '+36202543455',
        'vonalas_telefon'=> '',
        'cim'=> '1162 Budapest, Kendermag utca 9.',
        'szuletesi_ev'=> 1965,
        'szulinap'=> '03.11.',
        'nevnap'=> '03.12.',
        'email'=> 'gdobszay@gmail.com',
        'skype'=> 'gdobszay',
        'csaladsorszam'=> 4,
        'matebazsi_kod'=> 4,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=> '11773140-08392101',
        'revolut_id'=> '',
        'ki_ki'=> 1,
        'naptar'=> 1,
        'elso_generacio'=> 1,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszayné Triff Beatrix',
        'mobil_telefonszam'=> '+36202543485',
        'vonalas_telefon'=> '',
        'cim'=> '1162 Budapest, Kendermag utca 9.',
        'szuletesi_ev'=> 1966,
        'szulinap'=> '09.15.',
        'nevnap'=> '07.29.',
        'email'=> 'btriff15@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 4,
        'matebazsi_kod'=> 40,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> null,
        'naptar'=> null,
        'elso_generacio'=> 1,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Bálint',
        'mobil_telefonszam'=> '+36202543363',
        'vonalas_telefon'=> '',
        'cim'=> '1061 Budapest, Jókai tér 7. 3/28A',
        'szuletesi_ev'=> 1994,
        'szulinap'=> '04.14.',
        'nevnap'=> '02.14.',
        'email'=> 'dobszi14@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 4,
        'matebazsi_kod'=> 41,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> 1,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Marcsi',
        'mobil_telefonszam'=> '+36202543862',
        'vonalas_telefon'=> '',
        'cim'=> '1043 Budapest, Kassai utca 21.',
        'szuletesi_ev'=> 1996,
        'szulinap'=> '04.05.',
        'nevnap'=> '07.01.',
        'email'=> 'marcsid96@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 4,
        'matebazsi_kod'=> 42,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Fitori Mátyás Bence',
        'mobil_telefonszam'=> 36306485504,
        'vonalas_telefon'=> '',
        'cim'=> '2151 Fót, Széchenyi I. u. 41.',
        'szuletesi_ev'=> 1993,
        'szulinap'=> '05.25.',
        'nevnap'=> '02.24.',
        'email'=> 'fitorimatyasbence@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 4,
        'matebazsi_kod'=> 420,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno-vej',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Fitori Kinga',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '1043 Budapest, Kassai utca 21.',
        'szuletesi_ev'=> 2023,
        'szulinap'=> '08.17',
        'nevnap'=> '07.24',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 4,
        'matebazsi_kod'=> 421,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Kalapos-Dobszay Rita',
        'mobil_telefonszam'=> '+36202544871',
        'vonalas_telefon'=> '(+41779040863)',
        'cim'=> '1162 Budapest, Kendermag utca 9.',
        'szuletesi_ev'=> 1998,
        'szulinap'=> '10.12.',
        'nevnap'=> '05.22.',
        'email'=> 'vancsi01@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 4,
        'matebazsi_kod'=> 43,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Kalapos Péter',
        'mobil_telefonszam'=> '+36205410448',
        'vonalas_telefon'=> '',
        'cim'=> '1193 Budapest, Deák Ferenc utca 64.',
        'szuletesi_ev'=> 1998,
        'szulinap'=> '06.26',
        'nevnap'=> '04.29',
        'email'=> 'kalapos.peti@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 4,
        'matebazsi_kod'=> 430,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno-vej',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Mátyás',
        'mobil_telefonszam'=> '+36202545128',
        'vonalas_telefon'=> '',
        'cim'=> '1162 Budapest, Kendermag utca 9.',
        'szuletesi_ev'=> 2005,
        'szulinap'=> '10.24.',
        'nevnap'=> '02.24.',
        'email'=> 'dobszy21@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 4,
        'matebazsi_kod'=> 44,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Ambrus',
        'mobil_telefonszam'=> '06204348158',
        'vonalas_telefon'=> 3623341097,
        'cim'=> '1132, Budapest, Kresz Géza utca 44/46 III/24.',
        'szuletesi_ev'=> 1966,
        'szulinap'=> '12.04.',
        'nevnap'=> '04.04.',
        'email'=> 'dobszaya@gmail.com',
        'skype'=> 'dobszaya18',
        'csaladsorszam'=> 5,
        'matebazsi_kod'=> 5,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 1,
        'naptar'=> 1,
        'elso_generacio'=> 1,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Ambrusné Marcsi',
        'mobil_telefonszam'=> '06209346420',
        'vonalas_telefon'=> '0623341097',
        'cim'=> '1132, Budapest, Kresz Géza utca 44/46 III/24.',
        'szuletesi_ev'=> 1967,
        'szulinap'=> '11.18.',
        'nevnap'=> '07.26.',
        'email'=> 'dmarcsi67@freemail.hu',
        'skype'=> null,
        'csaladsorszam'=> 5,
        'matebazsi_kod'=> 50,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> null,
        'naptar'=> null,
        'elso_generacio'=> 1,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Balázs',
        'mobil_telefonszam'=> '06204393018',
        'vonalas_telefon'=> '-',
        'cim'=> '9090 Pannonhalma, Rákóczi Ferenc u. 9.',
        'szuletesi_ev'=> 1991,
        'szulinap'=> '05.18.',
        'nevnap'=> '02.03',
        'email'=> 'dobszayb18@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 5,
        'matebazsi_kod'=> 51,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> 1,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay-Dudás Eszter Éva',
        'mobil_telefonszam'=> '06303949882',
        'vonalas_telefon'=> '-',
        'cim'=> '9090 Pannonhalma, Rákóczi Ferenc u. 9.',
        'szuletesi_ev'=> 1992,
        'szulinap'=> '04.08.',
        'nevnap'=> '05.24.',
        'email'=> 'desztiti@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 5,
        'matebazsi_kod'=> 510,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno-meny',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Boldizsár',
        'mobil_telefonszam'=> 'Nincs!',
        'vonalas_telefon'=> '',
        'cim'=> '9090 Pannonhalma, Rákóczi Ferenc u. 9.',
        'szuletesi_ev'=> 2016,
        'szulinap'=> '12.18.',
        'nevnap'=> '01.06',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 5,
        'matebazsi_kod'=> 511,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Éva',
        'mobil_telefonszam'=> 'Nincs!',
        'vonalas_telefon'=> '',
        'cim'=> '9090 Pannonhalma, Rákóczi Ferenc u. 9.',
        'szuletesi_ev'=> 2020,
        'szulinap'=> '03.22.',
        'nevnap'=> '12.24.',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 5,
        'matebazsi_kod'=> 512,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Luca',
        'mobil_telefonszam'=> 'Nincs!',
        'vonalas_telefon'=> '',
        'cim'=> '9090 Pannonhalma, Rákóczi Ferenc u. 9.',
        'szuletesi_ev'=> '2021.',
        'szulinap'=> 11.01,
        'nevnap'=> 12.13,
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 5,
        'matebazsi_kod'=> 513,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Schulek-Tóthné Dobszay Julcsi',
        'mobil_telefonszam'=> '06204079850',
        'vonalas_telefon'=> '',
        'cim'=> '1022 Budapest Felvinci út 12. (2072 Zsámbék Szilágyság u. 1.)',
        'szuletesi_ev'=> 1994,
        'szulinap'=> '06.18',
        'nevnap'=> '05.22',
        'email'=> 'dobszayj14@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 5,
        'matebazsi_kod'=> 52,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> 1,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Schulek-Tóth Balázs',
        'mobil_telefonszam'=> '06202252312',
        'vonalas_telefon'=> '',
        'cim'=> '1022 Budapest Felvinci út 12. (1111 Budapest, Bartók Béla út 10-12.)',
        'szuletesi_ev'=> 1989,
        'szulinap'=> '04.22',
        'nevnap'=> '02.03',
        'email'=> 'stbalu@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 5,
        'matebazsi_kod'=> 520,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno-vej',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Schulek-Tóth Barnabás',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '1022 Budapest Felvinci út 12. (2072 Zsámbék Szilágyság u. 1.)',
        'szuletesi_ev'=> 2025,
        'szulinap'=> '01.03.',
        'nevnap'=> '06.11',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 5,
        'matebazsi_kod'=> 521,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Bori',
        'mobil_telefonszam'=> '06209320945',
        'vonalas_telefon'=> '',
        'cim'=> '2072 Zsámbék Szilágyság utca 1',
        'szuletesi_ev'=> 1997,
        'szulinap'=> '03.28.',
        'nevnap'=> '12.04.',
        'email'=> 'dobbori@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 5,
        'matebazsi_kod'=> 53,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Incze Dániel',
        'mobil_telefonszam'=> '06205524568',
        'vonalas_telefon'=> '',
        'cim'=> '2072 Zsámbék Szilágyság utca 1',
        'szuletesi_ev'=> 1996,
        'szulinap'=> 10.24,
        'nevnap'=> '07.21',
        'email'=> 'inczedani96@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 5,
        'matebazsi_kod'=> 530,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno-vej',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Incze János Benedek',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '2072 Zsámbék Szilágyság utca 1',
        'szuletesi_ev'=> 2022,
        'szulinap'=> 12.27,
        'nevnap'=> '06.24',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 5,
        'matebazsi_kod'=> 531,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Incze Soma Ambrus',
       'mobil_telefonszam'=>  null,
        'vonalas_telefon'=> '',
        'cim'=> '',
        'szuletesi_ev'=> 2024,
        'szulinap'=> 12.08,
        'nevnap'=> '',
        'email'=> null,
        'skype'=> null,
        'csaladsorszam'=> 5,
        'matebazsi_kod'=> 532,
        'sor_szamlalo'=> null,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'dédu',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> 1
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Anna',
        'mobil_telefonszam'=> '+36204234599',
        'vonalas_telefon'=> '',
        'cim'=> '2013 Pomáz, Török Ignác u. 15.',
        'szuletesi_ev'=> 1971,
        'szulinap'=> '06.17.',
        'nevnap'=> '07.26.',
        'email'=> 'adobszay@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 6,
        'matebazsi_kod'=> 6,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=> '10700392-11712303-51100005',
        'revolut_id'=> '',
        'ki_ki'=> 1,
        'naptar'=> 1,
        'elso_generacio'=> 1,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Zatykó Ferenc',
        'mobil_telefonszam'=> '+36306675253',
        'vonalas_telefon'=> '',
        'cim'=> '2016 Leányfalu, Pacsirta utca 4.',
        'szuletesi_ev'=> 1971,
        'szulinap'=> '04.27.',
        'nevnap'=> '12.03.',
        'email'=> 'fzatyko@gmail.com',
        'skype'=> 'fzatyko',
        'csaladsorszam'=> 6,
        'matebazsi_kod'=> 60,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> null,
        'naptar'=> null,
        'elso_generacio'=> 1,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Zatykó Levente',
        'mobil_telefonszam'=> '+36202806703',
        'vonalas_telefon'=> '',
        'cim'=> '2013 Pomáz, Török Ignác u. 15.',
        'szuletesi_ev'=> 2001,
        'szulinap'=> '02.28.',
        'nevnap'=> '06.18.',
        'email'=> 'zatykolevente@gmail.com',
        'skype'=> 'levipehell',
        'csaladsorszam'=> 6,
        'matebazsi_kod'=> 61,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Zatykó Ilona',
        'mobil_telefonszam'=> '+36203147582',
        'vonalas_telefon'=> '',
        'cim'=> '2013 Pomáz, Török Ignác u. 15.',
        'szuletesi_ev'=> 2003,
        'szulinap'=> '03.21.',
        'nevnap'=> '08.18.',
        'email'=> 'zatykoilus@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 6,
        'matebazsi_kod'=> 62,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Zatykó Tímea',
        'mobil_telefonszam'=> '+36209231080',
        'vonalas_telefon'=> '',
        'cim'=> '2013 Pomáz, Török Ignác u. 15.',
        'szuletesi_ev'=> 2005,
        'szulinap'=> '12.02.',
        'nevnap'=> '05.03.',
        'email'=> 'zatykotimi@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 6,
        'matebazsi_kod'=> 63,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 'uno',
        'naptar'=> null,
        'elso_generacio'=> null,
        'unoka_generacio'=> 1,
        'dedunoka_generacio'=> null,
      ]);
       familydata::factory()->create([
        'nev'=> 'Dobszay Márton Benedek',
        'mobil_telefonszam'=> '+36208232432',
        'vonalas_telefon'=> '',
        'cim'=> '1053 Budapest, Ferenciek tere 9.',
        'szuletesi_ev'=> 1975,
        'szulinap'=> '02.08.',
        'nevnap'=> '11.11.',
        'email'=> 'dobbmar@gmail.com',
        'skype'=> null,
        'csaladsorszam'=> 7,
        'matebazsi_kod'=> 7,
        'sor_szamlalo'=> 1,
        'becenev_sor'=> '',
        'bankszamla'=>  '',
        'revolut_id'=> '',
        'ki_ki'=> 1,
        'naptar'=> 1,
        'elso_generacio'=> 1,
        'unoka_generacio'=> null,
        'dedunoka_generacio'=> null,
      ]);
    }
}
